### ISSUE TITLE
Automatically paste the video when a never-before-seen user enters chat

### ISSUE THREAD

**Issue by molecularswords** [spiffomatic64/SpiffBot#185]
Add a function to check the viewers list every few seconds and check against a continuously updated list of previous viewers. If a viewer not in the list enters the channel have spiffbot automatically post the video and explanation.

**Comment by spiffomatic64** [comment]
awesome, should we wait until they say something? or just spam it (not calling them out)
I dont want to scare away lurkers

**Comment by molecularswords** [comment]
Yeah, that's probably better.

**Comment by spiffomatic64** [comment]
cool, but which do you like better, waiting until they say something first, or just pasting it (as long as we dont mention their name, they might assume its a spam-over-time thing)

**Comment by molecularswords** [comment]
It's probably less spammy to wait until someone says something. That's when they get auto-opted-in anyway right?

**Comment by spiffomatic64** [comment]
yep, I'll just add the printout to that conditional

**Comment by spiffomatic64** [comment]
or actually, you could too now that we have the fork/pull/merge thing working lol

**Comment by molecularswords** [comment]
I think I did it right, but please check any work that I do. I'm not very experienced with this sort of stuff.

**Comment by spiffomatic64** [comment]
will do :) Im trying to use it more as well, as my company is moving to git from svn lol
