### ISSUE TITLE
Come up with name/branding for itabob/spiff dual streaming

### ISSUE THREAD

**Issue by spiffomatic64** [spiffomatic64/SpiffBot#247]
including images/logos/etc

**Comment by Itabob** [comment]
Talking with a friend who is pretty good with logos and such - see if you can come up with something fancy. I am thinking more dorky and silly but who knows.

**Comment by spiffomatic64** [comment]
thoughts on branding with nicknames/descriptions?
like for me: "the professor", "Spiff", "Hacker", "Nerd", "Mr Robot", "ADD"
for you (Don't be offended by any of these, just making shit up): "Geek", "Spaz", "Giggles", "MLG", "ADHD", "Ita"

so example names would be like: Geek and Nerd, Ita and Spiff, Hacker and Spaz, Mr Robot and Giggles, ADHD and ADD

**Comment by Itabob** [comment]
Spiff and Ita // Ita and Spiff whatevs
